version: '2'
services:
  weblate:
    build: weblate
    links:
      - cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./weblate/environment
    restart: always
    depends_on:
      - cache
  ssh:
    image: vauxoo/docker-ssh
    volumes_from:
      - weblate
    links:
      - weblate
    depends_on:
      - weblate
  cache:
    image: memcached:1.4
    restart: always
volumes:
  weblate-data: {}
